[package]
org = "ballerinax"
name = "health.base"
version = "1.0.4"
distribution = "2201.6.0"
authors = ["Ballerina"]
keywords = ["Healthcare"]
repository= "https://github.com/ballerina-platform/module-ballerinax-health.base"
export = [
    "health.base",
    "health.base.error",
    "health.base.message",
    "health.base.auth"
]
